nombre_ies = {
    "UAUSTRAL": 'UNIVERSIDAD AUSTRAL DE CHILE',
    "UCMAULE": 'UNIVERSIDAD CATOLICA DEL MAULE',
    "PUCV": 'PONTIFICIA UNIVERSIDAD CATOLICA DE VALPARAISO',
    "UDT": 'UNIVERSIDAD DE TARAPACA',
    "PUC": 'PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE',
    "UFRO": 'UNIVERSIDAD DE LA FRONTERA',
    "UAH": 'UNIVERSIDAD ALBERTO HURTADO',
    "UAP": 'UNIVERSIDAD ARTURO PRAT',
    "UAC": 'UNIVERSIDAD AUTONOMA DE CHILE',
    "UCCRSH": 'UNIVERSIDAD CATOLICA CARDENAL RAUL SILVA HENRIQUEZ',
    "UCT": 'UNIVERSIDAD CATOLICA DE TEMUCO',
    "UCN": 'UNIVERSIDAD CATOLICA DEL NORTE',
    "UA": 'UNIVERSIDAD DE ANTOFAGASTA',
    "UDA": 'UNIVERSIDAD DE ATACAMA',
    "UAYSEN": 'UNIVERSIDAD DE AYSEN',
    "UDCH": 'UNIVERSIDAD DE CHILE',
    "UDEC": 'UNIVERSIDAD DE CONCEPCION',
    "ULS": 'UNIVERSIDAD DE LA SERENA',
    "ULAGOS": 'UNIVERSIDAD DE LOS LAGOS',
    "UMAG": 'UNIVERSIDAD DE MAGALLANES',
    "UDO": "UNIVERSIDAD DE O'HIGGINS",
    "UPA": 'UNIVERSIDAD DE PLAYA ANCHA DE CIENCIAS DE LA EDUCACION',
    "USACH": 'UNIVERSIDAD DE SANTIAGO DE CHILE',
    "UTALCA": 'UNIVERSIDAD DE TALCA',
    "UDV": 'UNIVERSIDAD DE VALPARAISO',
    "UBB": 'UNIVERSIDAD DEL BIO-BIO',
    "UDP": 'UNIVERSIDAD DIEGO PORTALES',
    "UMCE": 'UNIVERSIDAD METROPOLITANA DE CIENCIAS DE LA EDUCACION',
    "UTFSM": 'UNIVERSIDAD TECNICA FEDERICO SANTA MARIA',
    "UTEM": 'UNIVERSIDAD TECNOLOGICA METROPOLITANA',
    "UCDLSC": 'UNIVERSIDAD CATOLICA DE LA SANTISIMA CONCEPCION',
    "CFT-MAULE": 'CFT DE LA REGION DEL MAULE',
    "IP-ARCOS": 'IP DE ARTE Y COMUNICACION ARCOS',
    "CFT-ENAC": 'CFT DE ENAC',
    "CFT-CEDUC": 'CFT CEDUC - UCN',
    "CFT-ARAUCANIA": 'CFT-ARAUCANIA',
    "CFT-PUCV": 'CFT PUCV',
    "IP-SUBERCASEAUX": 'IP-SUBERCASEAUX',
    "CFT-SAN-AGUSTIN": 'CFT SAN AGUSTIN',
    "IP-MATTHEI": 'IP-MATTHEI',
    "CFT-LAGOS": 'CFT-LAGOS'
}

output_cols = [
    'jornada',
    'sede',
    'carrera',
    'codigo_unico',
    'institucion',
    'item_c_1',
    'sub_item_c_1_1',
    'sub_item_c_1_2',
    'sub_item_c_2_1',
    'sub_item_c_2_2',
    'sub_item_c_3_1',
    'sub_item_c_3_2',
    'sub_item_c_3_3',
    'sub_item_c_3_4',
    'item_m_1',
    'item_m_2',
    'item_m_3',
    'item_m_4',
    'sub_item_1_1_1',
    'sub_item_1_1_2',
    'sub_item_1_1_3',
    'item_1_2',
    'item_2_1',
    'item_2_2',
    'item_2_3',
    'item_2_4',
    'item_2_5',
    'item_3_1',
    'item_3_2',
    'item_3_3',
    'item_3_4',
    'item_3_5',
    'item_3_6',
    'item_4_1',
    'item_4_2',
    'tipoinst1',
    'tipoinst2',
    'tipoinst3',
    'regionsede',
    'provincia',
    'comunasede',
    'areaconocimiento',
    'oecdarea',
    'oecdsubarea',
    'areacarreragenerica',
    'tipo_institucion',
    'tipo_carrera',
    'caracteristica_plan_especial',
    'duracion_total',
    'grado_academico',
    'nivel_carrera',
    'acreditada',
    'puntaje_corte',
    'elegibilidad_beca_pedagogia',
    'pedagogia_medicina_otro',
    'vacantes_semestre1',
    'vacantes_semestre2',
    'arancel_matricula',
    'valor_titulacion',
    'costo_certificado_diploma',
    'arancel_anual',
    'subsistema'
]

output_cols_aux = [
    'jornada', 'sede', 'carrera', 'codigo_unico', 'institucion',
    'item_c_1', 'sub_item_c_1_1', 'sub_item_c_1_2', 'sub_item_c_2_1',
    'sub_item_c_2_2', 'sub_item_c_3_1', 'sub_item_c_3_2', 'sub_item_c_3_3',
    'sub_item_c_3_4', 'item_m_1', 'item_m_2', 'item_m_3', 'item_m_4',
    'tipoinst1', 'tipoinst2', 'tipoinst3', 'regionsede',
    'provincia', 'comunasede', 'areaconocimiento', 'oecdarea',
    'oecdsubarea', 'areacarreragenerica', 'tipo_institucion',
    'tipo_carrera', 'caracteristica_plan_especial', 'duracion_total',
    'grado_academico', 'nivel_carrera', 'acreditada', 'puntaje_corte',
    'elegibilidad_beca_pedagogia', 'pedagogia_medicina_otro',
    'vacantes_semestre1', 'vacantes_semestre2', 'arancel_matricula',
    'valor_titulacion', 'costo_certificado_diploma', 'arancel_anual',
    'subsistema'
]

label = {
    "sub_item_1_1_1": "Costos de JCE contratado indefinido o de planta (M$)",
    "sub_item_1_1_2": "Costos de JCE contratado a plazo fijo o contrata (M$)",
    "sub_item_1_1_3": "Costos de JCE a honorarios (M$)",
    "item_1_2": "Costos de personal académico que realiza actividades de apoyo docente (ayudantes de cátedra, "
                "tutores de campo clínico, tutores de práctica, mentores) (M$)",
    "item_2_1": "Costo de apoyo a la docencia (materiales de docencia, insumos de laboratorio o talleres) (M$)",
    "item_2_2": "Costo asociado al uso de salas, laboratorios, campo clínico, laboratorio, bibliotecas o arriendo de "
                "estos (reporte depende de propiedad, refiérase a manual) (M$)",
    "item_2_3": "Costo asociado a salidas a terreno (M$)",
    "item_2_4": "Depreciación y amortización anualizada de mobiliario (salas), equipamiento de las mismas, libros (M$)",
    "item_2_5": "Depreciación y amortización anualizada de equipos de laboratorios y maquinaria utilizada en "
                "prácticas o talleres (M$)",
    "item_3_1": "Costo de personal NO académico (Decanato, Escuela, Departamentos, Comunidad Académica, "
                "Administración de Campus) (M$)",
    "item_3_2": "Costos tecnológicos de apoyo a la docencia, incluyendo costos asociados al desarrollo y capacitación "
                "para su uso (licencias, plataformas web) ($M)",
    "item_3_3": "Otros costos de apoyo a la docencia (servicios de transporte, asignaciones de movilización, "
                "subvenciones de estudiantes varias) (M$)",
    "item_3_4": "Costos relacionados comunicaciones y difusión interna (M$)",
    "item_3_5": "Costos relacionados comunicaciones y difusión externa (M$)",
    "item_3_6": "Otros costos indirectos y de mantenimiento (gastos generales, servicios de aseo y ornato) (M$)",
    "item_4_1": "Costo de implementos y materiales utilizados en el proceso y provistos por la institución ($M)",
    "item_4_2": "Costo asociado a remuneraciones, honorarios y/o dietas de la comisión evaluadora, personal "
                "extraordinario para el proceso, tutores, entre otros ($M) ",
    "item_c_1": "Número de empleados de administración a nivel central",
    "sub_item_c_1_1": "Personal de nivel central con labores asociadas exclusivamente a actividades de pregrado (%)",
    "sub_item_c_1_2": "Personal de nivel central con labores asociadas  a actividades de pregrado y postgrado (%)",
    "item_c_2": "Costos de remuneraciones de personal de administración central - incluyendo beneficios (i.e. costos "
                "totales)",
    "sub_item_c_2_1": "Costo de las remuneraciones del personal con labores asociadas exclusivamente a actividades de "
                      "pregrado (M$)",
    "sub_item_c_2_2": "Costo de las remuneraciones del personal con actividades en pregrado y postgrado(M$)",
    "item_c_3": "Otros costos",
    "sub_item_c_3_1": "Costos de depreciación, reparación, mantención y seguros de inmuebles y mobiliario a nivel "
                      "central de pregrado (M$)",
    "sub_item_c_3_2": "Costo de tecnologías de información, soporte, servicios de despacho y correo asociados a "
                      "pregrado (M$)",
    "sub_item_c_3_3": "Costos de publicidad y difusión asociados a pregrado (M$)",
    "sub_item_c_3_4": "Otros costos generales de nivel central (e.g. gastos generales, fotocopias, materiales de "
                      "oficina, viajes del personal, viáticos)(M$) ",
    "item_m_1": "Número de empleados contratados extraordinariamente para el proceso (incluye notarios y su personal)",
    "item_m_2": "Costo total de personal contratado de forma extraordinaria para el proceso ($M)",
    "item_m_3": "Equipamiento implementado extraordinariamente para el proceso (habilitación de call centers, "
                "software, licencias, mobiliario) ($M)",
    "item_m_4": "Otros costos asociados al proceso (fotocopias, timbres, papeles) ($M)",
}

costos = [
    'sub_item_1_1_1',
    'sub_item_1_1_2',
    'sub_item_1_1_3',
    'item_1_2',
    'item_2_1',
    'item_2_2',
    'item_2_3',
    'item_2_4',
    'item_2_5',
    'item_3_1',
    'item_3_2',
    'item_3_3',
    'item_3_4',
    'item_3_5',
    'item_3_6',
    'item_4_1',
    'item_4_2',
    'item_c_1',
    'sub_item_c_1_1',
    'sub_item_c_1_2',
    'sub_item_c_2_1',
    'sub_item_c_2_2',
    'sub_item_c_3_1',
    'sub_item_c_3_2',
    'sub_item_c_3_3',
    'sub_item_c_3_4',
    'item_m_1',
    'item_m_2',
    'item_m_3',
    'item_m_4',
]

costos_codigo_unico = [
    'sub_item_1_1_1',
    'sub_item_1_1_2',
    'sub_item_1_1_3',
    'item_1_2',
    'item_2_1',
    'item_2_2',
    'item_2_3',
    'item_2_4',
    'item_2_5',
    'item_3_1',
    'item_3_2',
    'item_3_3',
    'item_3_4',
    'item_3_5',
    'item_3_6',
    'item_4_1',
    'item_4_2',
]

costos_ies = [
    'item_c_1',
    'sub_item_c_1_1',
    'sub_item_c_1_2',
    'sub_item_c_2_1',
    'sub_item_c_2_2',
    'sub_item_c_3_1',
    'sub_item_c_3_2',
    'sub_item_c_3_3',
    'sub_item_c_3_4',
    'item_m_1',
    'item_m_2',
    'item_m_3',
    'item_m_4',
]

costos_matricula = [
    'item_m_1',
    'item_m_2',
    'item_m_3',
    'item_m_4',
]
